### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by icfly2** [TyXe-BDL/TyXe#16]
TyXe is recomended to be used instead of Pyro HiddenLayers, but it looks like it is pinned to an older version of Pyro. What is the development status of this library?

I'd be happy to contribute, there are some marked first issues, but before adding work I'd like to find out what the original authors have in mind with this package.

**Comment by icfly2** [comment]
I was hoping to initially use it for some classification problems on tabular data with different prior distributions (some Normal, some Poisson, some Binomial etc). 

I'd be happy to help with makign it compatible with the latest pyro and pytorch, but probably won't be able to do it alone. Also hosted docs somewhere and publishing to pypi would be nice, and something I'm happy to help with. 

I assume from the lack of development you aren't using this package anywhere anymore?

**Comment by ucl-jhr** [comment]
Thanks for your work on #18 ! I'll look into setting up continuous integration and publishing to pypi this week.

Regarding hosting docs, we have set up basic API docs on [readthedocs](https://tyxe.readthedocs.io/en/latest/). Obviously missing tutorials and would probably benefit from spending a bit more time with sphinx to make them look prettier.
