### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by julioasotodv** [TyXe-BDL/TyXe#27]
Hi,

I was looking for BNN libraries related to PyTorch for my next project and I found TyXe. 

However, I am unsure on whether this library is still being maintained. Any clues?

Thank you!

**Comment by hpplyt** [comment]
Hi, we haven't been working on the library lately as is probably apparent from the lack of activity on the repo :)

I'm happy to do some basic maintenance (e.g. bump the pytorch/pyro versions if that helps) or answer questions. If what you're planning to do seems feasible based on the examples, it should still be fine to use the library.

Let me know if that helps.

**Comment by julioasotodv** [comment]
@ucl-jhr thank you for reaching out! I have done some minor tests and everything works as expected for now. 

I'll let you know otherwise.

Thanks! I’ll now close the issue
